'use client'

import { useState, useRef } from 'react'

const voices = [
  {
    id: 'milo',
    name: 'Milo',
    description: 'Warm male — confident, slightly techy',
    file: '/voice/agentbot-voice-milo.mp3',
    script: "Welcome to Agentbot. Your personal AI agent is now live and ready to work for you, 24/7. I can monitor your inbox, manage your tasks, and handle payments while you sleep. Let's build something amazing together.",
    badge: 'Male',
  },
  {
    id: 'mia',
    name: 'Mia',
    description: 'Warm female — friendly, playful',
    file: '/voice/agentbot-voice-mia.mp3',
    script: "Hey there! I'm your Agentbot assistant. I just checked your inbox — you've got three urgent emails, your calendar is clear tomorrow, and your X thread about jungle music is getting a lot of traction. Want me to draft some replies?",
    badge: 'Female',
  },
  {
    id: 'chloe',
    name: 'Chloe',
    description: 'Professional — calm briefing style',
    file: '/voice/agentbot-voice-chloe.mp3',
    script: "Good morning. Here is your daily briefing. Platform health is nominal — all systems green. Revenue this week is up 12 percent. Three new users signed up overnight. Your MiMo token usage is within budget.",
    badge: 'Female',
  },
  {
    id: 'dean',
    name: 'Dean',
    description: 'Deep, authoritative — edge',
    file: '/voice/agentbot-voice-dean.mp3',
    script: "Alert. Unauthorized access attempt detected on your wallet. I've already locked the session, rotated your API keys, and sent you a notification. Your funds are safe. Security protocol Agentbot Shield is now active.",
    badge: 'Male',
  },
  {
    id: 'bingtang',
    name: '冰糖 (Bingtang)',
    description: 'Chinese — warm, professional',
    file: '/voice/agentbot-voice-bingtang-cn.mp3',
    script: '欢迎使用 Agentbot。您的AI助手已上线，随时为您服务。我可以帮您监控邮件、管理任务、处理支付。',
    badge: '中文',
  },
]

export default function VoiceDemoPage() {
  const [playing, setPlaying] = useState<string | null>(null)
  const audioRef = useRef<HTMLAudioElement | null>(null)

  const playVoice = (id: string, file: string) => {
    if (audioRef.current) {
      audioRef.current.pause()
    }
    const audio = new Audio(file)
    audioRef.current = audio
    audio.play()
    setPlaying(id)
    audio.onended = () => setPlaying(null)
  }

  const stopVoice = () => {
    if (audioRef.current) {
      audioRef.current.pause()
      audioRef.current = null
    }
    setPlaying(null)
  }

  return (
    <main className="min-h-screen bg-black text-white font-mono">
      <div className="max-w-4xl mx-auto px-6 py-16">
        {/* Header */}
        <section className="mb-16">
          <div className="inline-block px-3 py-1 border border-zinc-800 text-orange-500 text-[10px] uppercase tracking-widest mb-8">
            MiMo V2.5 TTS
          </div>
          <h1 className="text-4xl sm:text-6xl font-bold tracking-tighter uppercase leading-[0.9] mb-4">
            Agentbot <span className="text-orange-500">Voice.</span>
          </h1>
          <p className="text-zinc-500 text-sm max-w-lg leading-relaxed">
            Every voice you hear is generated by MiMo V2.5 TTS — no recording studios, no voice actors.
            One API call. 16 seconds. Five distinct personalities.
          </p>
        </section>

        {/* Voice Cards */}
        <section className="space-y-px">
          {voices.map((voice) => (
            <div
              key={voice.id}
              className="bg-zinc-950 border border-zinc-900 p-6 hover:border-zinc-800 transition-colors"
            >
              <div className="flex items-start justify-between gap-4 mb-4">
                <div>
                  <div className="flex items-center gap-3 mb-1">
                    <h2 className="text-lg font-bold tracking-tight">{voice.name}</h2>
                    <span className="text-[9px] uppercase tracking-widest text-orange-500 border border-orange-500/30 px-2 py-0.5">
                      {voice.badge}
                    </span>
                    {playing === voice.id && (
                      <span className="text-[9px] uppercase tracking-widest text-green-500 animate-pulse">
                        ▶ Playing
                      </span>
                    )}
                  </div>
                  <p className="text-xs text-zinc-600">{voice.description}</p>
                </div>
                <button
                  onClick={() =>
                    playing === voice.id
                      ? stopVoice()
                      : playVoice(voice.id, voice.file)
                  }
                  className={`px-4 py-2 text-xs font-bold uppercase tracking-widest transition-colors shrink-0 ${
                    playing === voice.id
                      ? 'bg-red-500 text-white hover:bg-red-400'
                      : 'bg-orange-500 text-black hover:bg-orange-400'
                  }`}
                >
                  {playing === voice.id ? 'Stop' : 'Play'}
                </button>
              </div>
              <p className="text-xs text-zinc-500 leading-relaxed italic">
                &ldquo;{voice.script}&rdquo;
              </p>
            </div>
          ))}
        </section>

        {/* Tech Details */}
        <section className="mt-16 border-t border-zinc-900 pt-16">
          <div className="text-[10px] uppercase tracking-widest text-zinc-600 mb-6">Technical Details</div>
          <div className="grid sm:grid-cols-3 gap-px bg-zinc-900">
            <div className="bg-black p-6">
              <div className="text-[9px] uppercase tracking-widest text-zinc-600 mb-2">Model</div>
              <div className="text-sm font-bold">MiMo V2.5 TTS</div>
            </div>
            <div className="bg-black p-6">
              <div className="text-[9px] uppercase tracking-widest text-zinc-600 mb-2">Provider</div>
              <div className="text-sm font-bold">Xiaomi MiMo</div>
            </div>
            <div className="bg-black p-6">
              <div className="text-[9px] uppercase tracking-widest text-zinc-600 mb-2">Latency</div>
              <div className="text-sm font-bold">~2s per clip</div>
            </div>
          </div>
        </section>

        {/* CTA */}
        <section className="mt-16 border-t border-zinc-900 pt-16">
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-6">
            <div>
              <h3 className="text-sm font-bold uppercase tracking-wider mb-1">Want your agent to speak?</h3>
              <p className="text-xs text-zinc-600">Voice is available on all Agentbot plans. BYOK or included.</p>
            </div>
            <a
              href="/signup"
              className="px-6 py-3 bg-white text-black text-xs font-bold uppercase tracking-widest hover:bg-zinc-200 transition-colors"
            >
              Get Started
            </a>
          </div>
        </section>

        {/* Footer */}
        <section className="mt-16 border-t border-zinc-900 pt-8">
          <div className="flex gap-4">
            <a href="/" className="text-[10px] uppercase tracking-widest text-zinc-600 hover:text-white transition-colors">Home</a>
            <a href="/pricing" className="text-[10px] uppercase tracking-widest text-zinc-600 hover:text-white transition-colors">Pricing</a>
            <a href="/documentation" className="text-[10px] uppercase tracking-widest text-zinc-600 hover:text-white transition-colors">Docs</a>
          </div>
        </section>
      </div>
    </main>
  )
}
