import { NextRequest, NextResponse } from 'next/server'
import { getClientIP, isRateLimited } from '@/app/lib/security-middleware'
import {
  gatewayUpstreamHeaders,
  normalizeGatewayModel,
  resolveGatewayUpstreams,
  shouldTryNextGatewayUpstream,
} from '@/app/lib/opengateway'

export const runtime = 'nodejs'
export const maxDuration = 120

type PlaygroundFile = {
  path: string
  language: string
  content: string
}

type PlaygroundGeneration = {
  title: string
  summary: string
  previewHtml: string
  files: PlaygroundFile[]
  console: string[]
}

const DEFAULT_MODEL = 'xiaomi/mimo-v2.5-pro'
const PLAYGROUND_MAX_TOKENS = 6000

const ALLOWED_PATHS = new Set([
  '.gitignore',
  'AGENTS.md',
  'bun.lock',
  'index.html',
  'package.json',
  'src/App.tsx',
  'src/index.css',
  'src/main.tsx',
  'src/vite-env.d.ts',
  'tsconfig.app.json',
  'tsconfig.json',
  'tsconfig.node.json',
  'vite.config.ts',
  'vercel.json',
  'README.md',
])

const EXAMPLE_PROMPTS = [
  'AI startup landing',
  'Habit tracker',
  'Pipeline CRM',
  'Designer portfolio',
]

function jsonResponse(error: string, status: number, details?: Record<string, unknown>) {
  return NextResponse.json({ error, ...details }, { status })
}

function userFacingGenerationError(error: unknown) {
  const message = error instanceof Error ? error.message : 'Generation failed'

  if (/JSON repair returned no content|Model response did not include JSON|Generation payload is not an object/i.test(message)) {
    return 'OpenClaude did not return valid app files. Try sending again; if it keeps happening, check the configured AI Gateway key and model access.'
  }

  if (/401|403|authentication|unauthorized|forbidden|invalid api key/i.test(message)) {
    return 'Playground model access is not authorized. Sign in and make sure the AI Gateway API key is configured for xiaomi/mimo-v2.5-pro.'
  }

  if (/429|rate limit|rate limits|temporarily have rate limits|free credits/i.test(message)) {
    return 'Vercel AI Gateway is rate limited for this key. Add paid credits or try again later; the playground is still using Agentbot Vercel AI Gateway.'
  }

  if (/Vercel AI Gateway is not configured|Playground model backend is not configured/i.test(message)) {
    return 'Playground model backend is not configured. Add AI_GATEWAY_API_KEY or VERCEL_AI_GATEWAY_KEY for Agentbot Vercel AI Gateway.'
  }

  return message
}

function asString(value: unknown, fallback = ''): string {
  return typeof value === 'string' ? value : fallback
}

function safePath(path: string): boolean {
  return ALLOWED_PATHS.has(path) && !path.includes('..') && !path.startsWith('/')
}

function normalizeFilePath(path: string) {
  const trimmed = path.trim().replace(/^\/+/, '')
  if (trimmed === 'App.tsx') return 'src/App.tsx'
  if (trimmed === 'index.css' || trimmed === 'App.css') return 'src/index.css'
  return trimmed
}

function scaffoldFiles(): PlaygroundFile[] {
  return [
    { path: '.gitignore', language: 'gitignore', content: 'node_modules\ndist\ndist-ssr\n.DS_Store\n*.local\n.env.local\n.env.*.local\n' },
    { path: 'AGENTS.md', language: 'markdown', content: '# Playground Project\n\nGenerated by Agentbot Playground.\n' },
    { path: 'bun.lock', language: 'text', content: '# Playground lockfile placeholder.\n' },
    { path: 'index.html', language: 'html', content: '<!doctype html>\n<html lang="en">\n<head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><title>Agentbot Playground</title></head>\n<body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body>\n</html>\n' },
    { path: 'package.json', language: 'json', content: '{\n  "scripts": { "dev": "vite --host 0.0.0.0", "build": "tsc -b && vite build", "preview": "vite preview --host 0.0.0.0" },\n  "dependencies": { "@vitejs/plugin-react": "latest", "vite": "latest", "typescript": "latest", "react": "latest", "react-dom": "latest" },\n  "devDependencies": { "@types/react": "latest", "@types/react-dom": "latest" }\n}\n' },
    { path: 'src/main.tsx', language: 'tsx', content: "import React from 'react'\nimport ReactDOM from 'react-dom/client'\nimport App from './App'\nimport './index.css'\n\nReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>)\n" },
    { path: 'src/vite-env.d.ts', language: 'typescript', content: '/// <reference types="vite/client" />\n' },
    { path: 'tsconfig.app.json', language: 'json', content: '{\n  "compilerOptions": { "target": "ES2020", "useDefineForClassFields": true, "lib": ["ES2020", "DOM", "DOM.Iterable"], "allowJs": false, "skipLibCheck": true, "esModuleInterop": true, "allowSyntheticDefaultImports": true, "strict": true, "forceConsistentCasingInFileNames": true, "module": "ESNext", "moduleResolution": "Bundler", "resolveJsonModule": true, "isolatedModules": true, "noEmit": true, "jsx": "react-jsx" },\n  "include": ["src"]\n}\n' },
    { path: 'tsconfig.json', language: 'json', content: '{ "files": [], "references": [{ "path": "./tsconfig.app.json" }, { "path": "./tsconfig.node.json" }] }\n' },
    { path: 'tsconfig.node.json', language: 'json', content: '{\n  "compilerOptions": { "target": "ES2022", "lib": ["ES2023"], "module": "ESNext", "skipLibCheck": true, "moduleResolution": "Bundler", "allowSyntheticDefaultImports": true, "strict": true, "noEmit": true },\n  "include": ["vite.config.ts"]\n}\n' },
    { path: 'vite.config.ts', language: 'typescript', content: "import { defineConfig } from 'vite'\nimport react from '@vitejs/plugin-react'\n\nexport default defineConfig({ plugins: [react()] })\n" },
    { path: 'vercel.json', language: 'json', content: '{ "framework": "vite", "buildCommand": "npm run build", "installCommand": "npm install", "outputDirectory": "dist" }\n' },
  ]
}

function extractJson(text: string): unknown {
  const trimmed = text.trim()
  const parseCandidate = (candidate: string) => {
    try {
      return JSON.parse(candidate)
    } catch (error) {
      if (error instanceof SyntaxError && /Bad escaped character/.test(error.message)) {
        return JSON.parse(candidate.replace(/\\(?!["\\/bfnrtu])/g, '\\\\'))
      }
      throw error
    }
  }

  if (trimmed.startsWith('{') && trimmed.endsWith('}')) {
    return parseCandidate(trimmed)
  }

  const fenced = trimmed.match(/```(?:json)?\s*([\s\S]*?)```/i)
  if (fenced?.[1]) {
    return parseCandidate(fenced[1].trim())
  }

  const first = trimmed.indexOf('{')
  const last = trimmed.lastIndexOf('}')
  if (first >= 0 && last > first) {
    return parseCandidate(trimmed.slice(first, last + 1))
  }

  throw new Error('Model response did not include JSON')
}

function normalizeGeneration(raw: unknown): PlaygroundGeneration {
  if (!raw || typeof raw !== 'object') {
    throw new Error('Generation payload is not an object')
  }

  const value = raw as Record<string, unknown>
  const title = asString(value.title, 'Untitled').slice(0, 80)
  const summary = asString(value.summary, 'OpenClaude generated a project draft.').slice(0, 240)
  const rawFiles = Array.isArray(value.files)
    ? value.files
    : value.files && typeof value.files === 'object'
      ? Object.entries(value.files as Record<string, unknown>).map(([path, content]) => (
          content && typeof content === 'object'
            ? { path, ...(content as Record<string, unknown>) }
            : { path, content }
        ))
      : [
          value.appTsx || value.app || value['src/App.tsx']
            ? { path: 'src/App.tsx', language: 'tsx', content: value.appTsx || value.app || value['src/App.tsx'] }
            : null,
          value.indexCss || value.css || value['src/index.css']
            ? { path: 'src/index.css', language: 'css', content: value.indexCss || value.css || value['src/index.css'] }
            : null,
        ].filter(Boolean)

  const files = rawFiles
    .map((file) => file && typeof file === 'object' ? file as Record<string, unknown> : null)
    .filter(Boolean)
    .map((file) => ({
      path: normalizeFilePath(asString(file?.path)),
      language: asString(file?.language, 'text').trim() || 'text',
      content: asString(file?.content),
    }))
    .filter((file) => safePath(file.path) && file.content.trim().length > 0)

  const completeFiles = [
    ...files,
    ...scaffoldFiles().filter((scaffold) => !files.some((file) => file.path === scaffold.path)),
  ].sort((a, b) => a.path.localeCompare(b.path))

  if (!completeFiles.some((file) => file.path === 'src/App.tsx') || !completeFiles.some((file) => file.path === 'src/index.css')) {
    throw new Error('Generation did not include editable files')
  }

  const previewHtml = asString(value.previewHtml).trim() || synthesizePreviewHtml(title, summary, completeFiles)

  return {
    title,
    summary,
    previewHtml,
    files: completeFiles,
    console: Array.isArray(value.console)
      ? value.console.map((line) => asString(line)).filter(Boolean).slice(0, 8)
      : ['OpenClaude wrote files', 'Preview updated'],
  }
}

function htmlEscape(value: string) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function synthesizePreviewHtml(title: string, summary: string, files: PlaygroundFile[]) {
  const appFile = files.find((file) => file.path === 'src/App.tsx')?.content || ''
  const cssFile = files.find((file) => file.path === 'src/index.css')?.content || ''
  const visibleText = Array.from(appFile.matchAll(/>([^<>{}\n]{3,80})</g))
    .map((match) => match[1]?.trim())
    .filter(Boolean)
    .slice(0, 6)

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <style>
    ${cssFile.slice(0, 5000)}
    body { min-height: 100vh; margin: 0; background: #050505; color: #fafafa; font-family: Inter, ui-sans-serif, system-ui, sans-serif; }
    .agentbot-preview { min-height: 100vh; display: grid; place-items: center; padding: 32px; background: radial-gradient(circle at top right, rgba(249, 115, 22, .2), transparent 30%), #050505; }
    .agentbot-preview-card { width: min(760px, 100%); border: 1px solid #27272a; background: rgba(9, 9, 11, .92); padding: 28px; }
    .agentbot-preview-kicker { color: #f97316; font: 700 11px/1 ui-monospace, SFMono-Regular, Menlo, monospace; letter-spacing: .18em; text-transform: uppercase; }
    .agentbot-preview h1 { margin: 12px 0; font-size: clamp(34px, 7vw, 72px); line-height: .95; }
    .agentbot-preview p, .agentbot-preview li { color: #a1a1aa; line-height: 1.65; }
  </style>
</head>
<body>
  <main class="agentbot-preview">
    <section class="agentbot-preview-card">
      <div class="agentbot-preview-kicker">Agentbot preview</div>
      <h1>${htmlEscape(title)}</h1>
      <p>${htmlEscape(summary)}</p>
      ${visibleText.length ? `<ul>${visibleText.map((item) => `<li>${htmlEscape(item)}</li>`).join('')}</ul>` : ''}
    </section>
  </main>
</body>
</html>`
}

function buildSystemPrompt(isIteration: boolean) {
  return `You are an app-builder assistant running inside Agentbot Playground.

Return ONLY valid JSON. Do not wrap it in markdown.

${isIteration
    ? 'The user already has an app. Apply their requested changes to the CURRENT FILES provided, preserving everything they did not ask to change. Return the complete updated files.'
    : "Build a small, polished React app from the user's request."} Output:
- title: short project title
- summary: one sentence
- files: produce only these editable app files:
  src/App.tsx, src/index.css
- console: 3-6 concise build log lines

Code requirements:
- Use React hooks where state is needed.
- Keep App.tsx self-contained and readable.
- Keep CSS in src/index.css.
- Keep src/App.tsx and src/index.css compact; under 160 lines each.
- Do not include previewHtml unless it is a short static preview under 1200 characters.
- Do not include secrets, external trackers, remote scripts, or network calls.
- Do not use markdown prose outside JSON.
- JSON strings must escape newlines correctly.`
}

type CurrentFile = { path: string; content: string }

function buildUserPrompt(prompt: string, currentFiles?: CurrentFile[]) {
  if (currentFiles && currentFiles.length > 0) {
    const fileBlocks = currentFiles
      .map((file) => `--- CURRENT FILE: ${file.path} ---\n${file.content.slice(0, 12_000)}`)
      .join('\n\n')
    return `Apply this change to the existing app:\n\n${prompt}\n\n${fileBlocks}\n\nReturn the full updated src/App.tsx and src/index.css.`
  }
  return `Create this app in the playground:\n\n${prompt}\n\nThe examples available in the UI are: ${EXAMPLE_PROMPTS.join(', ')}.`
}

function resolvePlaygroundGatewayUpstreams() {
  return resolveGatewayUpstreams().filter((upstream) => upstream.provider === 'vercel-ai-gateway')
}

async function repairGenerationJson(content: string, upstream: ReturnType<typeof resolveGatewayUpstreams>[number], model: string) {
  const response = await fetch(`${upstream.baseUrl}/chat/completions`, {
    method: 'POST',
    headers: gatewayUpstreamHeaders(upstream, 'Agentbot Playground'),
    body: JSON.stringify({
      model: normalizeGatewayModel(model, upstream.provider),
      messages: [
        {
          role: 'system',
          content: 'Repair the user payload into compact valid JSON only. Return title, summary, files, and console. Preserve src/App.tsx and src/index.css code content. Omit previewHtml unless it is already short and valid. Return no markdown.',
        },
        { role: 'user', content },
      ],
      temperature: 0,
      max_tokens: PLAYGROUND_MAX_TOKENS,
      ...(upstream.provider === 'openrouter' ? { reasoning: { max_tokens: 0 } } : {}),
    }),
    signal: AbortSignal.timeout(110_000),
  })

  if (!response.ok) {
    const text = await response.text().catch(() => '')
    throw new Error(`${upstream.provider} JSON repair failed with ${response.status}${text ? `: ${text.slice(0, 300)}` : ''}`)
  }

  const data = await response.json() as {
    choices?: Array<{ message?: { content?: string } }>
  }
  const repaired = data.choices?.[0]?.message?.content
  if (!repaired) {
    throw new Error(`${upstream.provider} JSON repair returned no content`)
  }

  return normalizeGeneration(extractJson(repaired))
}

async function generateWithVercelGateway(prompt: string, model: string, currentFiles?: CurrentFile[]) {
  const upstreams = resolvePlaygroundGatewayUpstreams()
  if (upstreams.length === 0) {
    throw new Error('Vercel AI Gateway is not configured.')
  }

  let lastFailure = ''

  for (const upstream of upstreams) {
    const response = await fetch(`${upstream.baseUrl}/chat/completions`, {
      method: 'POST',
      headers: gatewayUpstreamHeaders(upstream, 'Agentbot Playground'),
      body: JSON.stringify({
        model: normalizeGatewayModel(model, upstream.provider),
        messages: [
          { role: 'system', content: buildSystemPrompt(Boolean(currentFiles?.length)) },
          { role: 'user', content: buildUserPrompt(prompt, currentFiles) },
        ],
        temperature: 0.35,
        max_tokens: PLAYGROUND_MAX_TOKENS,
        ...(upstream.provider === 'openrouter' ? { reasoning: { max_tokens: 0 } } : {}),
      }),
      signal: AbortSignal.timeout(110_000),
    })

    if (!response.ok) {
      const text = await response.text().catch(() => '')
      lastFailure = `${upstream.provider} failed with ${response.status}${text ? `: ${text.slice(0, 300)}` : ''}`
      if (shouldTryNextGatewayUpstream(response.status)) continue
      throw new Error(lastFailure)
    }

    const data = await response.json() as {
      choices?: Array<{ message?: { content?: string } }>
    }
    const content = data.choices?.[0]?.message?.content
    if (!content) {
      lastFailure = `${upstream.provider} returned no content`
      continue
    }

    try {
      return normalizeGeneration(extractJson(content))
    } catch (parseError) {
      try {
        return await repairGenerationJson(content, upstream, model)
      } catch (repairError) {
        lastFailure = repairError instanceof Error
          ? repairError.message
          : parseError instanceof Error
            ? parseError.message
            : `${upstream.provider} returned invalid JSON`
        console.warn('[playground.generate] upstream returned invalid JSON', {
          provider: upstream.provider,
          error: lastFailure,
        })
        continue
      }
    }
  }

  throw new Error(lastFailure || 'All configured playground model upstreams failed.')
}

function localMockGeneration(prompt: string): PlaygroundGeneration {
  const title = prompt.split(/\s+/).filter(Boolean).slice(0, 4).join(' ') || 'Untitled'
  const safeTitle = title.replace(/[<>&"]/g, '')
  const appTsx = `import { useMemo, useState } from 'react'
import './index.css'

const seedItems = ['Research', 'Design', 'Build', 'Review']

export default function App() {
  const [active, setActive] = useState(seedItems[0])
  const progress = useMemo(() => seedItems.indexOf(active) + 1, [active])

  return (
    <main className="shell">
      <section className="hero">
        <p className="eyebrow">OpenClaude local draft</p>
        <h1>${safeTitle}</h1>
        <p>${prompt.replace(/`/g, '\\`')}</p>
      </section>
      <section className="panel">
        {seedItems.map((item) => (
          <button key={item} className={item === active ? 'active' : ''} onClick={() => setActive(item)}>
            {item}
          </button>
        ))}
      </section>
      <section className="meter" aria-label="Build progress">
        <span style={{ width: \`\${progress * 25}%\` }} />
      </section>
    </main>
  )
}
`
  const css = `:root {
  color: #fafafa;
  background: #050505;
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}

body {
  margin: 0;
}

.shell {
  min-height: 100vh;
  padding: 56px;
  background: radial-gradient(circle at top right, rgba(249, 115, 22, 0.18), transparent 28%), #050505;
}

.hero {
  max-width: 780px;
}

.eyebrow {
  color: #f97316;
  font-size: 12px;
  letter-spacing: 0.16em;
  text-transform: uppercase;
}

h1 {
  margin: 12px 0;
  font-size: clamp(42px, 8vw, 92px);
  line-height: 0.95;
  letter-spacing: -0.04em;
}

p {
  color: #a1a1aa;
  line-height: 1.7;
}

.panel {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
  gap: 1px;
  max-width: 720px;
  margin-top: 44px;
  background: #27272a;
}

button {
  border: 0;
  background: #09090b;
  color: #d4d4d8;
  padding: 22px;
  text-align: left;
  cursor: pointer;
}

button.active {
  color: #050505;
  background: #fafafa;
}

.meter {
  max-width: 720px;
  height: 8px;
  margin-top: 20px;
  background: #18181b;
}

.meter span {
  display: block;
  height: 100%;
  background: #f97316;
}`
  const packageJson = `{
  "scripts": {
    "dev": "vite --host 0.0.0.0",
    "build": "tsc -b && vite build",
    "preview": "vite preview --host 0.0.0.0"
  },
  "dependencies": {
    "@vitejs/plugin-react": "latest",
    "vite": "latest",
    "typescript": "latest",
    "react": "latest",
    "react-dom": "latest"
  },
  "devDependencies": {
    "@types/react": "latest",
    "@types/react-dom": "latest"
  }
}
`

  return {
    title: safeTitle,
    summary: 'Local mock generation is enabled for offline playground testing.',
    previewHtml: `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${css}</style></head><body><main class="shell"><section class="hero"><p class="eyebrow">OpenClaude local draft</p><h1>${safeTitle}</h1><p>${prompt.replace(/[<>&"]/g, '')}</p></section><section class="panel"><button class="active">Research</button><button>Design</button><button>Build</button><button>Review</button></section><section class="meter"><span style="width:50%"></span></section></main></body></html>`,
    files: [
      { path: '.gitignore', language: 'gitignore', content: 'node_modules\ndist\ndist-ssr\n.DS_Store\n*.local\n.env.local\n.env.*.local\n\n.vscode/*\n!.vscode/extensions.json\n.idea\n' },
      { path: 'AGENTS.md', language: 'markdown', content: '# Playground Project\n\nGenerated by Agentbot OpenClaude Playground.\n\n- Keep app code in `src/App.tsx`.\n- Keep styling in `src/index.css`.\n- Do not commit generated secrets or local environment files.\n' },
      { path: 'bun.lock', language: 'text', content: '# This playground lockfile is a local preview placeholder.\n' },
      { path: 'index.html', language: 'html', content: '<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="UTF-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n    <title>Agentbot Playground</title>\n  </head>\n  <body>\n    <div id="root"></div>\n    <script type="module" src="/src/main.tsx"></script>\n  </body>\n</html>\n' },
      { path: 'package.json', language: 'json', content: packageJson },
      { path: 'src/App.tsx', language: 'tsx', content: appTsx },
      { path: 'src/index.css', language: 'css', content: css },
      { path: 'src/main.tsx', language: 'tsx', content: "import React from 'react'\nimport ReactDOM from 'react-dom/client'\nimport App from './App'\nimport './index.css'\n\nReactDOM.createRoot(document.getElementById('root')!).render(\n  <React.StrictMode>\n    <App />\n  </React.StrictMode>,\n)\n" },
      { path: 'src/vite-env.d.ts', language: 'typescript', content: '/// <reference types="vite/client" />\n' },
      { path: 'tsconfig.app.json', language: 'json', content: '{\n  "compilerOptions": {\n    "tsBuildInfoFile": "./node_modules/.tmp/tsconfig.app.tsbuildinfo",\n    "target": "ES2020",\n    "useDefineForClassFields": true,\n    "lib": ["ES2020", "DOM", "DOM.Iterable"],\n    "allowJs": false,\n    "skipLibCheck": true,\n    "esModuleInterop": true,\n    "allowSyntheticDefaultImports": true,\n    "strict": true,\n    "forceConsistentCasingInFileNames": true,\n    "module": "ESNext",\n    "moduleResolution": "Bundler",\n    "resolveJsonModule": true,\n    "isolatedModules": true,\n    "noEmit": true,\n    "jsx": "react-jsx"\n  },\n  "include": ["src"]\n}\n' },
      { path: 'tsconfig.json', language: 'json', content: '{\n  "files": [],\n  "references": [\n    { "path": "./tsconfig.app.json" },\n    { "path": "./tsconfig.node.json" }\n  ]\n}\n' },
      { path: 'tsconfig.node.json', language: 'json', content: '{\n  "compilerOptions": {\n    "tsBuildInfoFile": "./node_modules/.tmp/tsconfig.node.tsbuildinfo",\n    "target": "ES2022",\n    "lib": ["ES2023"],\n    "module": "ESNext",\n    "skipLibCheck": true,\n    "moduleResolution": "Bundler",\n    "allowSyntheticDefaultImports": true,\n    "strict": true,\n    "noEmit": true\n  },\n  "include": ["vite.config.ts"]\n}\n' },
      { path: 'vite.config.ts', language: 'typescript', content: "import { defineConfig } from 'vite'\nimport react from '@vitejs/plugin-react'\n\nexport default defineConfig({\n  plugins: [react()],\n  server: {\n    host: '0.0.0.0',\n    port: 5173,\n  },\n})\n" },
      { path: 'vercel.json', language: 'json', content: '{\n  "framework": "vite",\n  "buildCommand": "npm run build",\n  "installCommand": "npm install",\n  "outputDirectory": "dist"\n}\n' },
    ],
    console: ['PLAYGROUND_ALLOW_LOCAL_MOCK=1', 'Generated Vite React TS project', 'Wrote 14 files', 'Preview updated'],
  }
}

export async function POST(req: NextRequest) {
  const ip = getClientIP(req)
  if (await isRateLimited(ip)) {
    return jsonResponse('Too many requests', 429)
  }

  let body: { prompt?: unknown; model?: unknown; files?: unknown } = {}
  try {
    body = await req.json()
  } catch {
    return jsonResponse('Invalid JSON body', 400)
  }

  const prompt = asString(body.prompt).trim()
  const model = asString(body.model, DEFAULT_MODEL).trim() || DEFAULT_MODEL

  // Optional current files → iteration mode (edit instead of regenerate)
  const currentFiles: CurrentFile[] = Array.isArray(body.files)
    ? (body.files as unknown[])
        .map((entry) => {
          const file = entry as { path?: unknown; content?: unknown }
          return { path: asString(file?.path), content: asString(file?.content) }
        })
        .filter((file) => (file.path === 'src/App.tsx' || file.path === 'src/index.css') && file.content.length > 0)
        .slice(0, 2)
    : []

  if (prompt.length < 12) {
    return jsonResponse('Describe the app in at least 12 characters.', 400)
  }
  if (prompt.length > 5000) {
    return jsonResponse('Prompt is too long for the playground.', 400)
  }

  try {
    if (process.env.PLAYGROUND_ALLOW_LOCAL_MOCK === '1') {
      return NextResponse.json({
        provider: 'local-mock',
        model,
        generation: localMockGeneration(prompt),
      })
    }

    if (resolvePlaygroundGatewayUpstreams().length > 0) {
      const generation = await generateWithVercelGateway(prompt, model, currentFiles.length > 0 ? currentFiles : undefined)
      return NextResponse.json({ provider: 'vercel-ai-gateway', model, generation })
    }

    return jsonResponse('Playground model backend is not configured.', 503, {
      requiredEnv: ['AI_GATEWAY_API_KEY', 'VERCEL_AI_GATEWAY_KEY'],
      localTestEnv: 'Set PLAYGROUND_ALLOW_LOCAL_MOCK=1 only for offline UI testing.',
    })
  } catch (error) {
    console.error('[playground.generate] failed', error)
    return jsonResponse(userFacingGenerationError(error), 502)
  }
}
