FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install --production

# Build
COPY . .
RUN npm run build

# Listen on all interfaces
ENV PORT=8080
EXPOSE 8080

CMD ["node", "dist/index.js"]
