/**
 * Playground generation — shared logic for the JSON and streaming endpoints.
 *
 * Multi-file apps: besides src/App.tsx and src/index.css, the model may write
 * components, hooks, lib modules, and extra stylesheets (sanitized patterns,
 * capped count/size). Scaffold files (vite config, tsconfig, package.json…)
 * are always supplied server-side and never model-controlled.
 */

export type PlaygroundFile = {
  path: string
  language: string
  content: string
}

export type PlaygroundGeneration = {
  title: string
  summary: string
  previewHtml: string
  files: PlaygroundFile[]
  console: string[]
}

export type CurrentFile = { path: string; content: string }

export const MAX_MODEL_FILES = 16
export const MAX_FILE_CHARS = 24_000
export const MAX_TOTAL_CHARS = 200_000

const SCAFFOLD_PATHS = new Set([
  '.gitignore',
  'AGENTS.md',
  'bun.lock',
  'index.html',
  'package.json',
  'src/main.tsx',
  'src/vite-env.d.ts',
  'tsconfig.app.json',
  'tsconfig.json',
  'tsconfig.node.json',
  'vite.config.ts',
  'vercel.json',
  'README.md',
])

/** Dynamic, model-writable app files */
const DYNAMIC_FILE_RE =
  /^src\/(?:App\.tsx|index\.css|(?:components|hooks|lib)\/[A-Za-z0-9_-]{1,48}\.(?:tsx|ts)|[A-Za-z0-9_-]{1,48}\.css)$/

export function isModelWritablePath(path: string): boolean {
  return DYNAMIC_FILE_RE.test(path) && !path.includes('..')
}

export function safePath(path: string): boolean {
  if (path.includes('..') || path.startsWith('/')) return false
  return SCAFFOLD_PATHS.has(path) || DYNAMIC_FILE_RE.test(path)
}

export function normalizeFilePath(path: string) {
  const trimmed = path.trim().replace(/^\/+/, '').replace(/^\.\//, '')
  if (trimmed === 'App.tsx') return 'src/App.tsx'
  if (trimmed === 'index.css' || trimmed === 'App.css') return 'src/index.css'
  if (/^(components|hooks|lib)\//.test(trimmed)) return `src/${trimmed}`
  return trimmed
}

export function inferLanguage(path: string) {
  if (path.endsWith('.tsx')) return 'tsx'
  if (path.endsWith('.ts')) return 'typescript'
  if (path.endsWith('.css')) return 'css'
  if (path.endsWith('.json')) return 'json'
  if (path.endsWith('.html')) return 'html'
  if (path.endsWith('.md')) return 'markdown'
  return 'text'
}

function asString(value: unknown, fallback = ''): string {
  return typeof value === 'string' ? value : fallback
}

export function scaffoldFiles(): PlaygroundFile[] {
  return [
    { path: '.gitignore', language: 'gitignore', content: 'node_modules\ndist\ndist-ssr\n.DS_Store\n*.local\n.env.local\n.env.*.local\n' },
    { path: 'AGENTS.md', language: 'markdown', content: '# Playground Project\n\nGenerated by Agentbot Playground.\n' },
    { path: 'bun.lock', language: 'text', content: '# Playground lockfile placeholder.\n' },
    { path: 'index.html', language: 'html', content: '<!doctype html>\n<html lang="en">\n<head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><title>Agentbot Playground</title></head>\n<body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body>\n</html>\n' },
    { path: 'package.json', language: 'json', content: '{\n  "scripts": { "dev": "vite --host 0.0.0.0", "build": "tsc -b && vite build", "preview": "vite preview --host 0.0.0.0" },\n  "dependencies": { "@vitejs/plugin-react": "latest", "vite": "latest", "typescript": "latest", "react": "latest", "react-dom": "latest" },\n  "devDependencies": { "@types/react": "latest", "@types/react-dom": "latest" }\n}\n' },
    { path: 'src/main.tsx', language: 'tsx', content: "import React from 'react'\nimport ReactDOM from 'react-dom/client'\nimport App from './App'\nimport './index.css'\n\nReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>)\n" },
    { path: 'src/vite-env.d.ts', language: 'typescript', content: '/// <reference types="vite/client" />\n' },
    { path: 'tsconfig.app.json', language: 'json', content: '{\n  "compilerOptions": { "target": "ES2020", "useDefineForClassFields": true, "lib": ["ES2020", "DOM", "DOM.Iterable"], "allowJs": false, "skipLibCheck": true, "esModuleInterop": true, "allowSyntheticDefaultImports": true, "strict": true, "forceConsistentCasingInFileNames": true, "module": "ESNext", "moduleResolution": "Bundler", "resolveJsonModule": true, "isolatedModules": true, "noEmit": true, "jsx": "react-jsx" },\n  "include": ["src"]\n}\n' },
    { path: 'tsconfig.json', language: 'json', content: '{ "files": [], "references": [{ "path": "./tsconfig.app.json" }, { "path": "./tsconfig.node.json" }] }\n' },
    { path: 'tsconfig.node.json', language: 'json', content: '{\n  "compilerOptions": { "target": "ES2022", "lib": ["ES2023"], "module": "ESNext", "skipLibCheck": true, "moduleResolution": "Bundler", "allowSyntheticDefaultImports": true, "strict": true, "noEmit": true },\n  "include": ["vite.config.ts"]\n}\n' },
    { path: 'vite.config.ts', language: 'typescript', content: "import { defineConfig } from 'vite'\nimport react from '@vitejs/plugin-react'\n\nexport default defineConfig({ plugins: [react()] })\n" },
    { path: 'vercel.json', language: 'json', content: '{ "framework": "vite", "buildCommand": "npm run build", "installCommand": "npm install", "outputDirectory": "dist" }\n' },
  ]
}

function htmlEscape(value: string) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

export function synthesizePreviewHtml(title: string, summary: string, files: PlaygroundFile[]) {
  const cssFile = files.find((file) => file.path === 'src/index.css')?.content || ''
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <style>${cssFile.slice(0, 5000)}</style>
</head>
<body>
  <main style="min-height:100vh;display:grid;place-items:center;background:#050505;color:#fafafa;font-family:ui-monospace,monospace">
    <section style="max-width:640px;padding:28px;border:1px solid #27272a">
      <h1>${htmlEscape(title)}</h1>
      <p style="color:#a1a1aa">${htmlEscape(summary)}</p>
    </section>
  </main>
</body>
</html>`
}

/** Sanitize model-provided files: allowlisted paths, per-file and total caps. */
export function sanitizeModelFiles(rawFiles: Array<{ path?: unknown; language?: unknown; content?: unknown }>): PlaygroundFile[] {
  let total = 0
  const seen = new Set<string>()
  const out: PlaygroundFile[] = []

  for (const raw of rawFiles) {
    if (out.length >= MAX_MODEL_FILES) break
    const path = normalizeFilePath(asString(raw?.path))
    const content = asString(raw?.content).slice(0, MAX_FILE_CHARS)
    if (!isModelWritablePath(path) || seen.has(path) || content.trim().length === 0) continue
    if (total + content.length > MAX_TOTAL_CHARS) break
    seen.add(path)
    total += content.length
    out.push({ path, language: asString(raw?.language).trim() || inferLanguage(path), content })
  }

  return out
}

/** Compose a complete generation from sanitized model files + scaffold. */
export function composeGeneration(params: {
  title: string
  summary: string
  modelFiles: PlaygroundFile[]
  console?: string[]
  previewHtml?: string
}): PlaygroundGeneration {
  const title = params.title.slice(0, 80) || 'Untitled'
  const summary = params.summary.slice(0, 240) || 'OpenClaude generated a project draft.'
  const files = [
    ...params.modelFiles,
    ...scaffoldFiles().filter((scaffold) => !params.modelFiles.some((file) => file.path === scaffold.path)),
  ].sort((a, b) => a.path.localeCompare(b.path))

  if (!files.some((file) => file.path === 'src/App.tsx') || !files.some((file) => file.path === 'src/index.css')) {
    throw new Error('Generation did not include editable files')
  }

  return {
    title,
    summary,
    previewHtml: params.previewHtml?.trim() || synthesizePreviewHtml(title, summary, files),
    files,
    console: (params.console ?? ['OpenClaude wrote files', 'Preview updated']).slice(0, 8),
  }
}

export function normalizeGeneration(raw: unknown): PlaygroundGeneration {
  if (!raw || typeof raw !== 'object') {
    throw new Error('Generation payload is not an object')
  }

  const value = raw as Record<string, unknown>
  const rawFiles = Array.isArray(value.files)
    ? value.files
    : value.files && typeof value.files === 'object'
      ? Object.entries(value.files as Record<string, unknown>).map(([path, content]) => (
          content && typeof content === 'object'
            ? { path, ...(content as Record<string, unknown>) }
            : { path, content }
        ))
      : [
          value.appTsx || value.app || value['src/App.tsx']
            ? { path: 'src/App.tsx', language: 'tsx', content: value.appTsx || value.app || value['src/App.tsx'] }
            : null,
          value.indexCss || value.css || value['src/index.css']
            ? { path: 'src/index.css', language: 'css', content: value.indexCss || value.css || value['src/index.css'] }
            : null,
        ].filter(Boolean)

  const modelFiles = sanitizeModelFiles(
    rawFiles.map((file) => (file && typeof file === 'object' ? (file as Record<string, unknown>) : {})),
  )

  return composeGeneration({
    title: asString(value.title, 'Untitled'),
    summary: asString(value.summary, 'OpenClaude generated a project draft.'),
    modelFiles,
    previewHtml: asString(value.previewHtml),
    console: Array.isArray(value.console)
      ? value.console.map((line) => asString(line)).filter(Boolean)
      : undefined,
  })
}

export function extractJson(text: string): unknown {
  const trimmed = text.trim()
  const parseCandidate = (candidate: string) => {
    try {
      return JSON.parse(candidate)
    } catch (error) {
      if (error instanceof SyntaxError && /Bad escaped character/.test(error.message)) {
        return JSON.parse(candidate.replace(/\\(?!["\\/bfnrtu])/g, '\\\\'))
      }
      throw error
    }
  }

  if (trimmed.startsWith('{') && trimmed.endsWith('}')) {
    return parseCandidate(trimmed)
  }

  const fenced = trimmed.match(/```(?:json)?\s*([\s\S]*?)```/i)
  if (fenced?.[1]) {
    return parseCandidate(fenced[1].trim())
  }

  const first = trimmed.indexOf('{')
  const last = trimmed.lastIndexOf('}')
  if (first >= 0 && last > first) {
    return parseCandidate(trimmed.slice(first, last + 1))
  }

  throw new Error('Model response did not include JSON')
}

const FILE_RULES = `File rules:
- Always include src/App.tsx and src/index.css.
- You may also create: src/components/<Name>.tsx, src/hooks/<name>.ts, src/lib/<name>.ts, and extra src/<name>.css files (max ${MAX_MODEL_FILES} files total).
- Use relative imports between your files (e.g. import Header from './components/Header').
- Only react and react-dom are available — no other npm packages.
- No secrets, trackers, remote scripts, or network calls.`

export function buildJsonSystemPrompt(isIteration: boolean) {
  return `You are an app-builder assistant running inside Agentbot Playground.

Return ONLY valid JSON. Do not wrap it in markdown.

${isIteration
    ? 'The user already has an app. Apply their requested changes to the CURRENT FILES provided, preserving everything they did not ask to change. Return ALL files of the app, complete and updated.'
    : "Build a polished React app from the user's request."} Output:
- title: short project title
- summary: one sentence
- files: array of { path, content }
- console: 3-6 concise build log lines

${FILE_RULES}
- Do not include previewHtml.
- JSON strings must escape newlines correctly.`
}

/**
 * Marker format for the streaming endpoint — far easier to parse
 * incrementally than JSON:
 *
 *   @@@TITLE: My App
 *   @@@SUMMARY: One sentence.
 *   @@@FILE: src/App.tsx
 *   ...complete file content...
 *   @@@FILE: src/index.css
 *   ...complete file content...
 *   @@@DONE
 */
export function buildStreamSystemPrompt(isIteration: boolean) {
  return `You are an app-builder assistant running inside Agentbot Playground.

${isIteration
    ? 'The user already has an app. Apply their requested changes to the CURRENT FILES provided, preserving everything they did not ask to change. Output ALL files of the app, complete and updated.'
    : "Build a polished React app from the user's request."}

Respond in EXACTLY this plain-text format (no markdown, no code fences):

@@@TITLE: <short project title>
@@@SUMMARY: <one sentence>
@@@FILE: src/App.tsx
<complete file content>
@@@FILE: src/index.css
<complete file content>
@@@DONE

${FILE_RULES}
- Every file starts with an @@@FILE: line and runs until the next @@@ marker.
- Finish with @@@DONE on its own line.`
}

export function buildUserPrompt(prompt: string, currentFiles?: CurrentFile[]) {
  if (currentFiles && currentFiles.length > 0) {
    const fileBlocks = currentFiles
      .map((file) => `--- CURRENT FILE: ${file.path} ---\n${file.content.slice(0, 12_000)}`)
      .join('\n\n')
    return `Apply this change to the existing app:\n\n${prompt}\n\n${fileBlocks}\n\nReturn ALL app files, complete and updated.`
  }
  return `Create this app in the playground:\n\n${prompt}`
}

/**
 * Edit-mode (Fast Apply path): the model returns only the changed regions per
 * file as lazy edits with "// ... existing code ..." placeholders. The server
 * then Fast-Applies each edit against the current file — far cheaper than asking
 * the model to re-emit whole files on every follow-up.
 */
export type EditInstruction = { path: string; edit: string }

export function buildEditSystemPrompt() {
  return `You are editing an existing React app in Agentbot Playground.

Return ONLY valid JSON. No markdown fences. Shape:
{
  "title": "<short title>",
  "summary": "<one sentence describing the change>",
  "edits": [
    { "path": "src/App.tsx", "edit": "<lazy edit>" }
  ]
}

Lazy edit rules:
- Include ONLY the files you change. Do not touch files that don't need changes.
- In each edit, show the changed lines in context and replace unchanged regions
  with a single line: // ... existing code ...
- Keep enough surrounding lines that the change is unambiguous.
- Valid paths: src/App.tsx, src/index.css, src/components/<Name>.tsx,
  src/hooks/<name>.ts, src/lib/<name>.ts, src/<name>.css.
- Only react and react-dom are available. No other packages.
- JSON strings must escape newlines correctly.`
}

export function buildEditUserPrompt(prompt: string, currentFiles: CurrentFile[]) {
  const fileBlocks = currentFiles
    .map((file) => `--- CURRENT FILE: ${file.path} ---\n${file.content.slice(0, 12_000)}`)
    .join('\n\n')
  return `Make this change to the app:\n\n${prompt}\n\n${fileBlocks}\n\nReturn only the lazy edits for the files you change.`
}

/** Parse the edit-mode JSON payload into validated instructions. */
export function parseEditInstructions(raw: unknown): { title: string; summary: string; edits: EditInstruction[] } {
  if (!raw || typeof raw !== 'object') throw new Error('Edit payload is not an object')
  const value = raw as Record<string, unknown>
  const rawEdits = Array.isArray(value.edits) ? value.edits : []
  const edits: EditInstruction[] = []
  for (const entry of rawEdits) {
    if (!entry || typeof entry !== 'object') continue
    const e = entry as Record<string, unknown>
    const path = normalizeFilePath(asString(e.path))
    const edit = asString(e.edit)
    if (isModelWritablePath(path) && edit.trim().length > 0) edits.push({ path, edit })
  }
  return {
    title: asString(value.title, 'Untitled'),
    summary: asString(value.summary, 'Applied your changes.'),
    edits,
  }
}

/** Parse current-files payload from a request body (iteration mode). */
export function sanitizeCurrentFiles(raw: unknown): CurrentFile[] {
  if (!Array.isArray(raw)) return []
  let total = 0
  const out: CurrentFile[] = []
  for (const entry of raw as unknown[]) {
    if (out.length >= MAX_MODEL_FILES) break
    const file = entry as { path?: unknown; content?: unknown }
    const path = normalizeFilePath(asString(file?.path))
    const content = asString(file?.content)
    if (!isModelWritablePath(path) || content.length === 0) continue
    if (total + content.length > MAX_TOTAL_CHARS) break
    total += content.length
    out.push({ path, content })
  }
  return out
}

/**
 * Incremental parser for the @@@ marker stream format.
 * Feed chunks; it emits events and keeps partial state.
 */
export class MarkerStreamParser {
  private buffer = ''
  title = ''
  summary = ''
  files: { path: string; content: string }[] = []
  private currentPath: string | null = null
  done = false

  /** Returns events produced by this chunk. */
  push(chunk: string): Array<
    | { type: 'meta'; title: string; summary: string }
    | { type: 'file_open'; path: string }
    | { type: 'file_chunk'; path: string; text: string }
    | { type: 'file_close'; path: string; content: string }
    | { type: 'done' }
  > {
    this.buffer += chunk
    const events: ReturnType<MarkerStreamParser['push']> = []

    // Process complete lines; hold back the last partial line unless it can't
    // be a marker prefix (so file content streams promptly).
    while (true) {
      const newline = this.buffer.indexOf('\n')
      if (newline === -1) {
        // Flush non-marker partials into the open file for live streaming
        if (this.currentPath && this.buffer.length > 0 && !'@@@'.startsWith(this.buffer.slice(0, 3)) && !this.buffer.startsWith('@')) {
          events.push({ type: 'file_chunk', path: this.currentPath, text: this.buffer })
          this.appendToCurrent(this.buffer)
          this.buffer = ''
        }
        break
      }

      const line = this.buffer.slice(0, newline)
      this.buffer = this.buffer.slice(newline + 1)

      if (line.startsWith('@@@TITLE:')) {
        this.title = line.slice('@@@TITLE:'.length).trim()
        if (this.summary) events.push({ type: 'meta', title: this.title, summary: this.summary })
      } else if (line.startsWith('@@@SUMMARY:')) {
        this.summary = line.slice('@@@SUMMARY:'.length).trim()
        events.push({ type: 'meta', title: this.title, summary: this.summary })
      } else if (line.startsWith('@@@FILE:')) {
        this.closeCurrent(events)
        const path = normalizeFilePath(line.slice('@@@FILE:'.length).trim())
        if (isModelWritablePath(path)) {
          this.currentPath = path
          this.files.push({ path, content: '' })
          events.push({ type: 'file_open', path })
        } else {
          this.currentPath = null
        }
      } else if (line.startsWith('@@@DONE')) {
        this.closeCurrent(events)
        this.done = true
        events.push({ type: 'done' })
      } else if (this.currentPath) {
        const text = `${line}\n`
        events.push({ type: 'file_chunk', path: this.currentPath, text })
        this.appendToCurrent(text)
      }
    }

    return events
  }

  private appendToCurrent(text: string) {
    const file = this.files.find((item) => item.path === this.currentPath)
    if (file && file.content.length < MAX_FILE_CHARS) file.content += text
  }

  private closeCurrent(events: ReturnType<MarkerStreamParser['push']>) {
    if (!this.currentPath) return
    const file = this.files.find((item) => item.path === this.currentPath)
    if (file) {
      file.content = file.content.replace(/\n$/, '\n')
      events.push({ type: 'file_close', path: file.path, content: file.content })
    }
    this.currentPath = null
  }

  toGeneration(): PlaygroundGeneration {
    const modelFiles = sanitizeModelFiles(this.files.map((file) => ({ ...file, language: inferLanguage(file.path) })))
    return composeGeneration({
      title: this.title || 'Untitled',
      summary: this.summary || 'OpenClaude generated a project draft.',
      modelFiles,
      console: ['OpenClaude streamed files', 'Preview updated live'],
    })
  }
}
