import type { Metadata } from 'next'
import Link from 'next/link'
import { prisma } from '@/app/lib/prisma'
import { Prisma } from '@prisma/client'
import { normalizeGeneration, isMissingPlaygroundProjectTable, formatLastActive } from '@/app/api/playground/projects/_shared'

export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'

export const metadata: Metadata = {
  title: 'Apps Built on Agentbot — Playground Gallery',
  description:
    'Browse apps built with the Agentbot Playground. Remix any app free — describe, preview, publish, all in your browser.',
  openGraph: {
    title: 'Apps Built on Agentbot — Playground Gallery',
    description: 'Browse and remix apps built with the Agentbot Playground.',
    type: 'website',
    url: 'https://agentbot.sh/playground/gallery',
  },
}

type SharedApp = {
  id: string
  name: string
  title: string
  summary: string
  fileCount: number
  publishedUrl: string | null
  lastActive: string
}

async function loadSharedApps(): Promise<SharedApp[]> {
  const projects = await prisma.playgroundProject
    .findMany({
      where: {
        status: { not: 'ARCHIVED' },
        generation: { not: Prisma.DbNull },
      },
      select: {
        id: true,
        name: true,
        generation: true,
        publishedUrl: true,
        lastActiveAt: true,
        updatedAt: true,
      },
      orderBy: { lastActiveAt: 'desc' },
      take: 48,
    })
    .catch((error) => {
      if (isMissingPlaygroundProjectTable(error)) return []
      throw error
    })

  return projects
    .map((project) => {
      const generation = normalizeGeneration(project.generation)
      if (!generation) return null
      return {
        id: project.id,
        name: project.name,
        title: generation.title,
        summary: generation.summary,
        fileCount: generation.files.length,
        publishedUrl: project.publishedUrl,
        lastActive: formatLastActive(project.lastActiveAt ?? project.updatedAt),
      }
    })
    .filter(Boolean) as SharedApp[]
}

export default async function PlaygroundGallery() {
  const apps = await loadSharedApps()

  return (
    <main className="min-h-screen bg-black font-mono text-white">
      <div className="border-b border-zinc-900">
        <div className="mx-auto flex max-w-5xl items-center justify-between gap-3 px-5 py-3">
          <Link href="/playground" className="text-[11px] font-bold uppercase tracking-widest hover:text-orange-500">
            ◈ Agentbot Playground
          </Link>
          <Link
            href="/playground"
            className="bg-white px-3 py-1.5 text-[10px] font-bold uppercase tracking-widest text-black hover:bg-zinc-200"
          >
            Build an app
          </Link>
        </div>
      </div>

      <div className="mx-auto max-w-5xl px-5 py-10">
        <div className="mb-8">
          <div className="text-[10px] uppercase tracking-widest text-orange-500">Gallery</div>
          <h1 className="mt-3 text-3xl font-bold uppercase tracking-tighter sm:text-4xl">
            Apps built on Agentbot
          </h1>
          <p className="mt-3 max-w-2xl text-sm leading-relaxed text-zinc-500">
            Every app below was generated by AI in the Playground — prompt, preview, edit, publish.
            Click any app to preview the code and remix it.
          </p>
        </div>

        {apps.length === 0 ? (
          <div className="border border-zinc-900 bg-zinc-950 p-12 text-center">
            <div className="text-[10px] uppercase tracking-widest text-zinc-600">No apps yet</div>
            <p className="mt-3 text-sm text-zinc-500">
              Be the first to build and share an app on the Playground.
            </p>
            <Link
              href="/playground"
              className="mt-6 inline-block bg-white px-5 py-2.5 text-[10px] font-bold uppercase tracking-widest text-black hover:bg-zinc-200"
            >
              Build your first app →
            </Link>
          </div>
        ) : (
          <>
            <div className="mb-4 text-[10px] uppercase tracking-widest text-zinc-600">
              {apps.length} app{apps.length !== 1 ? 's' : ''}
            </div>
            <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
              {apps.map((app) => (
                <Link
                  key={app.id}
                  href={`/playground/s/${app.id}`}
                  className="group border border-zinc-900 bg-zinc-950 p-5 transition-colors hover:border-zinc-700"
                >
                  <div className="flex items-start justify-between gap-2">
                    <h2 className="text-sm font-bold uppercase tracking-tight leading-snug group-hover:text-orange-500">
                      {app.title}
                    </h2>
                    {app.publishedUrl && (
                      <span className="shrink-0 border border-zinc-800 px-1.5 py-0.5 text-[8px] uppercase tracking-widest text-zinc-600">
                        live
                      </span>
                    )}
                  </div>
                  {app.summary && (
                    <p className="mt-2 line-clamp-2 text-xs leading-relaxed text-zinc-500">
                      {app.summary}
                    </p>
                  )}
                  <div className="mt-3 flex items-center justify-between text-[9px] uppercase tracking-widest text-zinc-700">
                    <span>{app.fileCount} file{app.fileCount !== 1 ? 's' : ''}</span>
                    <span>{app.lastActive}</span>
                  </div>
                </Link>
              ))}
            </div>
          </>
        )}

        {/* Built in London — AAA Pass laminate */}
        <div className="mt-12 relative overflow-hidden border border-orange-500/40 bg-gradient-to-br from-zinc-950 to-black">
          {/* lanyard notch */}
          <div className="absolute left-1/2 top-0 h-3 w-16 -translate-x-1/2 rounded-b-full border border-t-0 border-orange-500/40 bg-black" aria-hidden="true" />
          <div className="grid gap-px sm:grid-cols-[1.4fr_1fr]">
            {/* left: the pitch */}
            <div className="p-8 sm:p-10">
              <div className="flex items-center gap-3 mb-5">
                <span className="inline-block border border-orange-500/50 px-2 py-1 text-[9px] font-bold uppercase tracking-[0.3em] text-orange-500">Access All Areas</span>
                <span className="text-[9px] uppercase tracking-[0.25em] text-zinc-600">Pass № 001</span>
              </div>
              <h2 className="text-2xl sm:text-3xl font-bold uppercase tracking-tighter leading-[0.95]">
                Built in London.<br />
                <span className="text-orange-500">Every agent gets the AAA pass.</span>
              </h2>
              <p className="mt-5 max-w-md text-sm leading-relaxed text-zinc-400">
                Designed and engineered in London for the people who run the culture — labels,
                collectives, promoters, producers. Your agent goes backstage by default: all channels,
                all skills, all hours. No guest list, no plus-one needed.
              </p>
              <div className="mt-6 flex flex-wrap gap-2">
                {['E1 Shoreditch', 'GMT · Always On', 'AAA Clearance'].map((chip) => (
                  <span key={chip} className="border border-zinc-800 px-3 py-1.5 text-[10px] uppercase tracking-widest text-zinc-400">{chip}</span>
                ))}
              </div>
            </div>
            {/* right: the laminate */}
            <div className="border-t border-orange-500/20 sm:border-t-0 sm:border-l p-8 sm:p-10 flex flex-col justify-between bg-black/40">
              <div>
                <div className="text-[9px] uppercase tracking-[0.3em] text-zinc-600 mb-2">Agentbot · Backstage</div>
                <div className="text-6xl font-bold tracking-tighter text-orange-500 leading-none">AAA</div>
                <div className="mt-2 text-[10px] uppercase tracking-[0.25em] text-zinc-500">Triple-A · Access All Areas</div>
              </div>
              {/* barcode */}
              <svg viewBox="0 0 220 44" className="mt-6 w-full" role="img" aria-label="Backstage pass barcode">
                {Array.from({ length: 48 }).map((_, i) => {
                  const w = (i * 7) % 5 < 2 ? 1.5 : i % 3 === 0 ? 3.5 : 2
                  const x = i * 4.5 + 2
                  return <rect key={i} x={x} y="2" width={w} height="30" fill={i % 9 === 0 ? '#f97316' : '#e4e4e7'} />
                })}
                <text x="2" y="42" fontFamily="ui-monospace,monospace" fontSize="7" fill="#52525b" letterSpacing="3">AGENTBOT · LDN · E1 · ALL HOURS</text>
              </svg>
            </div>
          </div>
        </div>

        {/* CTA */}
        <div className="mt-12 border border-zinc-900 bg-zinc-950 p-8 text-center">
          <h2 className="text-xl font-bold uppercase tracking-tighter">Build your own</h2>
          <p className="mx-auto mt-2 max-w-md text-sm text-zinc-500">
            Describe an app, watch it stream into a live preview, edit it, and publish — free, on the
            Agentbot Playground.
          </p>
          <Link
            href="/playground"
            className="mt-6 inline-block bg-white px-6 py-3 text-[10px] font-bold uppercase tracking-widest text-black hover:bg-zinc-200"
          >
            Open Playground →
          </Link>
        </div>
      </div>
    </main>
  )
}
