'use client'

import { useState, useEffect } from 'react'
import { Download, FileText, Calendar, Eye, Loader2 } from 'lucide-react'

interface InvoiceItem { description: string; quantity: number; unitPrice: number; amount: number }
interface RealInvoice {
  id: string
  invoiceNumber: string
  clientName?: string
  clientEmail?: string
  items?: InvoiceItem[]
  subtotal?: number
  taxRate?: number
  taxAmount?: number
  total?: number
  currency?: string
  status?: 'draft' | 'sent' | 'paid' | 'overdue'
  dueDate?: string
  notes?: string
  createdAt?: string
}

const STATUS_COLORS: Record<string, string> = {
  draft: 'text-zinc-500 border-zinc-700',
  sent: 'text-blue-400 border-blue-800',
  paid: 'text-green-400 border-green-800',
  overdue: 'text-red-400 border-red-800',
}

const cur = (c?: string) => (c === 'USD' ? '$' : '£')

export default function ExportPage() {
  const [invoices, setInvoices] = useState<RealInvoice[]>([])
  const [invoicesLoading, setInvoicesLoading] = useState(true)
  const [dateFrom, setDateFrom] = useState('2026-01-01')
  const [dateTo, setDateTo] = useState('2026-12-31')
  const [statusFilter, setStatusFilter] = useState('All')

  useEffect(() => {
    fetch('/api/invoice')
      .then((r) => r.json())
      .then((d) => { if (d.ok && Array.isArray(d.invoices)) setInvoices(d.invoices) })
      .catch(() => {})
      .finally(() => setInvoicesLoading(false))
  }, [])

  const openInvoice = (inv: RealInvoice) => {
    const s = cur(inv.currency)
    const rows = (inv.items || [])
      .map((it) => `<tr><td style="padding:8px;border-bottom:1px solid #eee">${it.description || ''}</td><td style="padding:8px;border-bottom:1px solid #eee;text-align:center">${it.quantity}</td><td style="padding:8px;border-bottom:1px solid #eee;text-align:right">${s}${(it.unitPrice || 0).toFixed(2)}</td><td style="padding:8px;border-bottom:1px solid #eee;text-align:right">${s}${(it.amount || 0).toFixed(2)}</td></tr>`)
      .join('')
    const html = `<!doctype html><html><head><meta charset="utf-8"><title>${inv.invoiceNumber}</title></head><body style="font-family:system-ui,sans-serif;max-width:720px;margin:40px auto;color:#111">
      <div style="display:flex;justify-content:space-between;align-items:flex-start"><div><h1 style="margin:0">Invoice ${inv.invoiceNumber}</h1><div style="color:#666;text-transform:uppercase;font-size:12px;letter-spacing:.1em;margin-top:4px">${inv.status || 'draft'}</div></div><div style="text-align:right;color:#666;font-size:13px">Due ${inv.dueDate || '—'}</div></div>
      <div style="margin:24px 0;color:#444"><strong>Bill To</strong><br>${inv.clientName || ''}<br>${inv.clientEmail || ''}</div>
      <table style="width:100%;border-collapse:collapse;font-size:14px"><thead><tr style="text-align:left;color:#888;font-size:12px;text-transform:uppercase"><th style="padding:8px">Description</th><th style="padding:8px;text-align:center">Qty</th><th style="padding:8px;text-align:right">Price</th><th style="padding:8px;text-align:right">Amount</th></tr></thead><tbody>${rows}</tbody></table>
      <div style="margin-top:24px;margin-left:auto;width:240px;font-size:14px">
        <div style="display:flex;justify-content:space-between;padding:4px 0"><span style="color:#666">Subtotal</span><span>${s}${(inv.subtotal || 0).toFixed(2)}</span></div>
        <div style="display:flex;justify-content:space-between;padding:4px 0"><span style="color:#666">Tax (${inv.taxRate || 0}%)</span><span>${s}${(inv.taxAmount || 0).toFixed(2)}</span></div>
        <div style="display:flex;justify-content:space-between;padding:8px 0;border-top:2px solid #111;font-weight:bold;font-size:16px"><span>Total</span><span>${s}${(inv.total || 0).toFixed(2)}</span></div>
      </div>
      ${inv.notes ? `<div style="margin-top:24px;color:#666;font-size:13px"><strong>Notes:</strong> ${inv.notes}</div>` : ''}
      <p style="margin-top:40px;color:#aaa;font-size:11px">Generated by Agentbot · agentbot.sh</p></body></html>`
    const w = window.open('', '_blank')
    if (w) { w.document.write(html); w.document.close() }
  }

  const invDate = (inv: RealInvoice) => (inv.createdAt || inv.dueDate || '').slice(0, 10)

  const filtered = invoices.filter((inv) => {
    const d = invDate(inv)
    const matchDate = !d || (d >= dateFrom && d <= dateTo)
    const matchStatus = statusFilter === 'All' || (inv.status || 'draft') === statusFilter
    return matchDate && matchStatus
  })

  const totalInvoiced = filtered.reduce((s, i) => s + (i.total || 0), 0)
  const totalPaid = filtered.filter((i) => i.status === 'paid').reduce((s, i) => s + (i.total || 0), 0)
  const totalOutstanding = filtered.filter((i) => i.status === 'sent').reduce((s, i) => s + (i.total || 0), 0)

  const exportCSV = () => {
    const headers = ['Invoice', 'Client', 'Status', 'Date', 'Due', 'Currency', 'Total']
    const rows = filtered.map((i) => [
      i.invoiceNumber,
      (i.clientName || '').replace(/,/g, ' '),
      i.status || 'draft',
      invDate(i),
      i.dueDate || '',
      i.currency || 'GBP',
      (i.total || 0).toFixed(2),
    ])
    const csv = [headers, ...rows].map((r) => r.join(',')).join('\n')
    const blob = new Blob([csv], { type: 'text/csv' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `agentbot-invoices-${dateFrom}-to-${dateTo}.csv`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <main className="min-h-screen bg-black text-white font-mono pt-14">
      <div className="max-w-5xl mx-auto px-6 py-12">
        <div className="flex items-center justify-between mb-8">
          <div>
            <div className="text-[10px] uppercase tracking-[0.24em] text-zinc-600 mb-2">Finance</div>
            <h1 className="text-3xl font-bold uppercase tracking-tight">Export</h1>
          </div>
          <button onClick={exportCSV} className="flex items-center gap-2 bg-green-600 hover:bg-green-500 text-white rounded-lg px-4 py-2.5 text-xs font-bold uppercase tracking-wider transition-colors">
            <Download className="h-4 w-4" />
            Export CSV
          </button>
        </div>

        {/* Filters */}
        <div className="rounded-xl border border-zinc-800 bg-zinc-950 p-4 mb-8">
          <div className="flex items-center gap-4 flex-wrap">
            <div className="flex items-center gap-2">
              <Calendar className="h-4 w-4 text-zinc-600" />
              <input type="date" value={dateFrom} onChange={(e) => setDateFrom(e.target.value)} className="bg-black border border-zinc-800 rounded-lg px-3 py-2 text-sm text-white focus:outline-none focus:border-green-500/50" />
              <span className="text-zinc-600">to</span>
              <input type="date" value={dateTo} onChange={(e) => setDateTo(e.target.value)} className="bg-black border border-zinc-800 rounded-lg px-3 py-2 text-sm text-white focus:outline-none focus:border-green-500/50" />
            </div>
            <select value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)} className="bg-black border border-zinc-800 rounded-lg px-3 py-2 text-sm text-white focus:outline-none">
              <option value="All">All Statuses</option>
              <option value="draft">Draft</option>
              <option value="sent">Sent</option>
              <option value="paid">Paid</option>
              <option value="overdue">Overdue</option>
            </select>
          </div>
        </div>

        {/* Summary */}
        <div className="grid grid-cols-3 gap-4 mb-8">
          <div className="rounded-xl border border-zinc-800 bg-zinc-950 p-4">
            <div className="text-[10px] uppercase tracking-widest text-zinc-600">Invoiced</div>
            <div className="mt-2 text-2xl font-bold">£{totalInvoiced.toFixed(2)}</div>
          </div>
          <div className="rounded-xl border border-zinc-800 bg-zinc-950 p-4">
            <div className="text-[10px] uppercase tracking-widest text-zinc-600">Paid</div>
            <div className="mt-2 text-2xl font-bold text-green-400">£{totalPaid.toFixed(2)}</div>
          </div>
          <div className="rounded-xl border border-zinc-800 bg-zinc-950 p-4">
            <div className="text-[10px] uppercase tracking-widest text-zinc-600">Outstanding</div>
            <div className="mt-2 text-2xl font-bold text-blue-400">£{totalOutstanding.toFixed(2)}</div>
          </div>
        </div>

        {/* Invoices — open & read any of them */}
        <div className="rounded-xl border border-zinc-800 bg-zinc-950 overflow-hidden">
          <div className="border-b border-zinc-800 px-4 py-3 flex items-center justify-between">
            <span className="text-[10px] uppercase tracking-widest text-zinc-600">Invoices &amp; Bills</span>
            <span className="text-[10px] uppercase tracking-widest text-zinc-700">{invoicesLoading ? 'Loading' : `${filtered.length} shown`}</span>
          </div>
          <table className="w-full">
            <thead>
              <tr className="border-b border-zinc-800">
                <th className="text-left text-[10px] uppercase tracking-widest text-zinc-600 px-4 py-3">Invoice</th>
                <th className="text-left text-[10px] uppercase tracking-widest text-zinc-600 px-4 py-3">Client</th>
                <th className="text-left text-[10px] uppercase tracking-widest text-zinc-600 px-4 py-3">Status</th>
                <th className="text-right text-[10px] uppercase tracking-widest text-zinc-600 px-4 py-3">Total</th>
                <th className="text-right text-[10px] uppercase tracking-widest text-zinc-600 px-4 py-3">Open</th>
              </tr>
            </thead>
            <tbody>
              {filtered.map((inv) => (
                <tr key={inv.id} className="border-b border-zinc-900 hover:bg-zinc-900/50">
                  <td className="px-4 py-3 text-sm text-white">{inv.invoiceNumber}</td>
                  <td className="px-4 py-3 text-sm text-zinc-400">{inv.clientName || '—'}</td>
                  <td className="px-4 py-3">
                    <span className={`text-[10px] px-2 py-0.5 rounded border ${STATUS_COLORS[inv.status || 'draft']}`}>{inv.status || 'draft'}</span>
                  </td>
                  <td className="px-4 py-3 text-sm text-right font-bold">{cur(inv.currency)}{(inv.total || 0).toFixed(2)}</td>
                  <td className="px-4 py-3 text-right">
                    <button onClick={() => openInvoice(inv)} title="Open & read" className="inline-flex items-center gap-1 text-zinc-500 hover:text-white transition-colors text-xs">
                      <Eye className="h-4 w-4" />
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
          {!invoicesLoading && filtered.length === 0 && (
            <div className="text-center py-12 text-zinc-600">
              <FileText className="h-10 w-10 mx-auto mb-3 opacity-30" />
              <p className="text-sm">No invoices in this range. Create one on the Invoices page.</p>
            </div>
          )}
          {invoicesLoading && <div className="text-center py-12 text-zinc-600 flex items-center justify-center gap-2"><Loader2 className="h-4 w-4 animate-spin" /> Loading invoices…</div>}
        </div>
      </div>
    </main>
  )
}
