// Generated by Eve. Do not edit by hand.

import * as module_0 from "../../agent/agent.ts";
import * as module_1 from "../../agent/channels/slack.ts";
import * as module_2 from "../../agent/channels/telegram.ts";
import * as module_3 from "../../agent/connections/github.ts";
import * as module_4 from "../../agent/connections/linear.ts";
import * as module_5 from "../../agent/connections/notion.ts";
import * as module_6 from "../../agent/connections/slack.ts";
import * as module_7 from "../../agent/tools/get_agent_status.ts";
import * as module_8 from "../../agent/tools/get_weather.ts";
import * as module_9 from "../../agent/tools/list_connections.ts";
import * as module_10 from "../../agent/tools/manage_schedules.ts";
import * as module_11 from "../../agent/tools/query_metrics.ts";
import * as module_12 from "../../agent/subagents/researcher.ts";
import * as module_13 from "../../agent/subagents/support.ts";

export const moduleMap = Object.freeze({
  "nodes": Object.freeze({
      "__root__": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_0,
                  "channels/slack.ts": module_1,
                  "channels/telegram.ts": module_2,
                  "connections/github.ts": module_3,
                  "connections/linear.ts": module_4,
                  "connections/notion.ts": module_5,
                  "connections/slack.ts": module_6,
                  "tools/get_agent_status.ts": module_7,
                  "tools/get_weather.ts": module_8,
                  "tools/list_connections.ts": module_9,
                  "tools/manage_schedules.ts": module_10,
                  "tools/query_metrics.ts": module_11
                })
            }),
      "subagents/researcher.ts": Object.freeze({
              "modules": Object.freeze({
                  "subagents/researcher.ts": module_12
                })
            }),
      "subagents/support.ts": Object.freeze({
              "modules": Object.freeze({
                  "subagents/support.ts": module_13
                })
            })
    })
});

export default moduleMap;
